from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def __init__(self):
        super(Ui_GameWindow, self).__init__()

    def playUi(self, GameWindow, level_structure, sectors):
        GameWindow.setObjectName("GameWindow")
        GameWindow.resize(832, 896)
        self.groundCounter = 0
        self.verticalLayout = QtWidgets.QVBoxLayout(GameWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GameGUI = QtWidgets.QWidget(GameWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GameGUI.sizePolicy().hasHeightForWidth())
        self.GameGUI.setSizePolicy(sizePolicy)
        self.GameGUI.setObjectName("GameGUI")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.GameGUI)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.playZone = QtWidgets.QWidget(self.GameGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playZone.sizePolicy().hasHeightForWidth())
        self.playZone.setSizePolicy(sizePolicy)
        self.playZone.setObjectName("playZone")
        self.gridLayout = QtWidgets.QGridLayout(self.playZone)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        n_sector = 0
        for n_string in range(len(level_structure)):
            column = 0
            for symbol in level_structure[n_string].rstrip():
                n_se = sectors - n_sector
                if symbol == "W":
                    exec(f'self.wall{n_se} = QtWidgets.QLabel(self.playZone)')
                    exec(f'self.wall{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                    exec(f'self.wall{n_se}.setText("")')
                    exec(f'self.wall{n_se}.setPixmap(QtGui.QPixmap("../grafika/AirBanTexW.jpg"))')
                    exec(f'self.wall{n_se}.setObjectName("wall{n_se}")')
                    exec(f'self.gridLayout.addWidget(self.wall{n_se}, {n_string}, {column}, 1, 1)')
                elif symbol == "G":
                    exec(f'self.ground{n_se} = QtWidgets.QLabel(self.playZone)')
                    exec(f'self.ground{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                    exec(f'self.ground{n_se}.setText("")')
                    exec(f'self.ground{n_se}.setPixmap(QtGui.QPixmap("../grafika/AirBanTexG.jpg"))')
                    exec(f'self.ground{n_se}.setObjectName("ground{n_se}")')
                    exec(f'self.gridLayout.addWidget(self.ground{n_se}, {n_string}, {column}, 1, 1)')
                else:
                    if symbol == "F":
                        exec(f'self.finish{n_se} = QtWidgets.QLabel(self.playZone)')
                        exec(f'self.finish{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                        exec(f'self.finish{n_se}.setText("")')
                        exec(f'self.finish{n_se}.setPixmap(QtGui.QPixmap("../grafika/AirBanTexF.jpg"))')
                        exec(f'self.finish{n_se}.setObjectName("finish{n_se}")')
                        exec(f'self.gridLayout.addWidget(self.finish{n_se}, {n_string}, {column}, 1, 1)')
                    else:
                        exec(f'self.troll{n_se} = QtWidgets.QLabel(self.playZone)')
                        exec(f'self.troll{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                        exec(f'self.troll{n_se}.setText("")')
                        exec(f'self.troll{n_se}.setPixmap(QtGui.QPixmap("../grafika/AirBanTexT.jpg"))')
                        exec(f'self.troll{n_se}.setObjectName("troll{n_se}")')
                        exec(f'self.gridLayout.addWidget(self.troll{n_se}, {n_string}, {column}, 1, 1)')
                n_sector += 1
                column += 1
        self.verticalLayout_3.addWidget(self.playZone)
        self.hud = QtWidgets.QWidget(self.GameGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hud.sizePolicy().hasHeightForWidth())
        self.hud.setSizePolicy(sizePolicy)
        self.hud.setMaximumSize(QtCore.QSize(16777215, 64))
        self.hud.setObjectName("hud")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hud)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout_2")
        self.leftButton = QtWidgets.QPushButton(self.hud)
        self.leftButton.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.leftButton.setFont(font)
        self.leftButton.setText("🠔")
        self.leftButton.setIconSize(QtCore.QSize(16, 16))
        self.leftButton.setObjectName("leftButton")
        self.horizontalLayout.addWidget(self.leftButton)
        self.upButton = QtWidgets.QPushButton(self.hud)
        self.upButton.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.upButton.setFont(font)
        self.upButton.setText("🠕")
        self.upButton.setIconSize(QtCore.QSize(16, 16))
        self.upButton.setObjectName("upButton")
        self.horizontalLayout.addWidget(self.upButton)
        self.playerState = QtWidgets.QLabel(self.hud)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playerState.sizePolicy().hasHeightForWidth())
        self.playerState.setSizePolicy(sizePolicy)
        self.playerState.setMaximumSize(QtCore.QSize(96, 64))
        self.playerState.setText("")
        self.playerState.setPixmap(QtGui.QPixmap("../grafika/AirBanTexTLiv.jpg"))
        self.playerState.setObjectName("playerState")
        self.horizontalLayout.addWidget(self.playerState)
        self.exitButton_2 = QtWidgets.QPushButton(self.hud)
        self.exitButton_2.setMaximumSize(QtCore.QSize(32, 64))
        self.exitButton_2.setText("exit")
        self.exitButton_2.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton_2)
        self.downButton = QtWidgets.QPushButton(self.hud)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.downButton.setFont(font)
        self.downButton.setText("🠗")
        self.downButton.setIconSize(QtCore.QSize(16, 16))
        self.downButton.setObjectName("downButton")
        self.horizontalLayout.addWidget(self.downButton)
        self.rightButton = QtWidgets.QPushButton(self.hud)
        self.rightButton.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.rightButton.setFont(font)
        self.rightButton.setText("🠖")
        self.rightButton.setIconSize(QtCore.QSize(16, 16))
        self.rightButton.setObjectName("rightButton")
        self.horizontalLayout.addWidget(self.rightButton)
        self.verticalLayout_3.addWidget(self.hud)
        self.verticalLayout.addWidget(self.GameGUI)

        self.retranslateUi(GameWindow)
        QtCore.QMetaObject.connectSlotsByName(GameWindow)

    def retranslateUi(self, GameWindow):
        _translate = QtCore.QCoreApplication.translate
        GameWindow.setWindowTitle(_translate("GameWindow", "Game"))

    def create_hummers(self, hummers_count):
        for i in range(hummers_count):
            exec(f'self.hummer{i} = QtWidgets.QLabel(self.playZone)')
            exec(f'self.hummer{i}.setMaximumSize(QtCore.QSize(64, 64))')
            exec(f'self.hummer{i}.setText("")')
            exec(f'self.hummer{i}.setPixmap(QtGui.QPixmap("../grafika/AirBanTexX.jpg"))')
            exec(f'self.hummer{i}.setObjectName("hummer{i}")')
            exec(f'self.hummer{i}.hide()')
