from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Soft(object):
    def setupUi(self, Soft, GameWindow, level_structure, sectors):
        Soft.setObjectName("Soft")
        Soft.resize(1029, 800)
        self.centralWindow = QtWidgets.QWidget(Soft)
        self.centralWindow.setObjectName("centralWindow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.windowManager = QtWidgets.QWidget(self.centralWindow)
        self.windowManager.setObjectName("windowManager")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.windowManager)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.interpreterWidgets = QtWidgets.QWidget(self.windowManager)
        self.interpreterWidgets.setMinimumSize(QtCore.QSize(500, 0))
        self.interpreterWidgets.setObjectName("interpreterWidgets")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.interpreterWidgets)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.interpreterWidgets)
        self.tabWidget.setMaximumSize(QtCore.QSize(2660, 2660))
        self.tabWidget.setObjectName("tabWidget")
        self.plusTabWidjet = QtWidgets.QWidget()
        self.plusTabWidjet.setObjectName("plusTabWidjet")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plusTabWidjet)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.plusTabWidjet, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_2.addWidget(self.interpreterWidgets)
        self.boardWigets = QtWidgets.QWidget(self.windowManager)
        self.boardWigets.setMinimumSize(QtCore.QSize(500, 0))
        self.boardWigets.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boardWigets.setObjectName("boardWigets")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.boardWigets)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonsSorter = QtWidgets.QWidget(self.boardWigets)
        self.buttonsSorter.setMaximumSize(QtCore.QSize(16777215, 60))
        self.buttonsSorter.setObjectName("buttonsSorter")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.buttonsSorter)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.runButton = QtWidgets.QPushButton(self.buttonsSorter)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_4.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(self.buttonsSorter)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.verticalLayout.addWidget(self.buttonsSorter)
        self.playZone = QtWidgets.QWidget(self.windowManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playZone.sizePolicy().hasHeightForWidth())
        self.playZone.setSizePolicy(sizePolicy)
        self.playZone.setObjectName("playZone")
        self.gridLayout = QtWidgets.QGridLayout(self.playZone)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        n_sector = 0
        for n_string in range(len(level_structure)):
            column = 0
            for symbol in level_structure[n_string].rstrip():
                n_se = sectors - n_sector
                if symbol == "W":
                    exec(f'self.wall{n_se} = QtWidgets.QLabel(self.playZone)')
                    exec(f'self.wall{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                    exec(f'self.wall{n_se}.setText("")')
                    exec(f'self.wall{n_se}.setPixmap(QtGui.QPixmap("textures/PredInterpreterW.jpg"))')
                    exec(f'self.wall{n_se}.setObjectName("wall{n_se}")')
                    exec(f'self.gridLayout.addWidget(self.wall{n_se}, {n_string}, {column}, 1, 1)')
                elif symbol == "G":
                    exec(f'self.ground{n_se} = QtWidgets.QLabel(self.playZone)')
                    exec(f'self.ground{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                    exec(f'self.ground{n_se}.setText("")')
                    exec(f'self.ground{n_se}.setPixmap(QtGui.QPixmap("textures/PredInterpreterG.jpg"))')
                    exec(f'self.ground{n_se}.setObjectName("ground{n_se}")')
                    exec(f'self.gridLayout.addWidget(self.ground{n_se}, {n_string}, {column}, 1, 1)')
                else:
                    if symbol == "F":
                        exec(f'self.finish{n_se} = QtWidgets.QLabel(self.playZone)')
                        exec(f'self.finish{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                        exec(f'self.finish{n_se}.setText("")')
                        exec(f'self.finish{n_se}.setPixmap(QtGui.QPixmap("textures/PredInterpreterF.jpg"))')
                        exec(f'self.finish{n_se}.setObjectName("finish{n_se}")')
                        exec(f'self.gridLayout.addWidget(self.finish{n_se}, {n_string}, {column}, 1, 1)')
                    else:
                        exec(f'self.troll{n_se} = QtWidgets.QLabel(self.playZone)')
                        exec(f'self.troll{n_se}.setMaximumSize(QtCore.QSize(64, 64))')
                        exec(f'self.troll{n_se}.setText("")')
                        exec(f'self.troll{n_se}.setPixmap(QtGui.QPixmap("textures/PredInterpreterT.jpg"))')
                        exec(f'self.troll{n_se}.setObjectName("troll{n_se}")')
                        exec(f'self.gridLayout.addWidget(self.troll{n_se}, {n_string}, {column}, 1, 1)')
                n_sector += 1
                column += 1
        self.verticalLayout.addWidget(self.playZone)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.boardWigets)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 250))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_2.addWidget(self.boardWigets, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.windowManager)
        Soft.setCentralWidget(self.centralWindow)
        self.statusbar = QtWidgets.QStatusBar(Soft)
        self.statusbar.setObjectName("statusbar")
        Soft.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Soft)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1029, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        Soft.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(Soft)
        self.action.setObjectName("action")
        self.action_4 = QtWidgets.QAction(Soft)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(Soft)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(Soft)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(Soft)
        self.action_9.setObjectName("action_9")
        self.action_11 = QtWidgets.QAction(Soft)
        self.action_11.setObjectName("action_11")
        self.action_13 = QtWidgets.QAction(Soft)
        self.action_13.setObjectName("action_13")
        self.action_15 = QtWidgets.QAction(Soft)
        self.action_15.setObjectName("action_15")
        self.action_17 = QtWidgets.QAction(Soft)
        self.action_17.setObjectName("action_17")
        self.action_2 = QtWidgets.QAction(Soft)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Soft)
        self.action_3.setObjectName("action_3")
        self.action_6 = QtWidgets.QAction(Soft)
        self.action_6.setObjectName("action_6")
        self.action_8 = QtWidgets.QAction(Soft)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(Soft)
        self.action_9.setObjectName("action_8")
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_6)
        self.menu.addSeparator()
        self.menu.addAction(self.action_8)
        self.menu.addSeparator()
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_13)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_15)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_9)
        self.menu_2.addSeparator()
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Soft)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Soft)

    def retranslateUi(self, Soft):
        _translate = QtCore.QCoreApplication.translate
        Soft.setWindowTitle(_translate("Soft", "Интерпритатор"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plusTabWidjet), _translate("Soft", "+"))
        self.runButton.setText(_translate("Soft", "run"))
        self.stopButton.setText(_translate("Soft", "stop"))
        self.menu.setTitle(_translate("Soft", "Файл"))
        self.menu_2.setTitle(_translate("Soft", "Настройки"))
        self.action.setText(_translate("Soft", "Сохранить"))
        self.action_4.setText(_translate("Soft", "Сохранить"))
        self.action_5.setText(_translate("Soft", "Удалить"))
        self.action_7.setText(_translate("Soft", "Загрузить"))
        self.action_9.setText(_translate("Soft", "Сохранить"))
        self.action_11.setText(_translate("Soft", "Сохранить как"))
        self.action_13.setText(_translate("Soft", "Фон"))
        self.action_15.setText(_translate("Soft", "Шрифт"))
        self.action_2.setText(_translate("Soft", "Создать"))
        self.action_3.setText(_translate("Soft", "Открыть"))
        self.action_6.setText(_translate("Soft", "Сохранить как"))
        self.action_8.setText(_translate("Soft", "Удалить"))
        self.action_9.setText(_translate("Soft", "О приложении"))

