[SINGLE_KEYWORDS.tokens]
UP = "print()"
DOWN = "print()"
LEFT = "print()"
RIGHT = "print()"
SET = "print()"
CALL = "print()"
NUMERIC = "print()"

[SINGLE_KEYWORDS.token_masks]
UP = "^UP \\d+$"
DOWN = "^DOWN \\d+$"
LEFT = "^LEFT \\d+$"
RIGHT = "^RIGHT \\d+$"
SET = "^SET [a-zA-Z]+[ \t]*=[ \t]*\\d+$"
CALL = "^CALL[ \t]+[a-zA-Z]+$"
NUMERIC = "^\\d+$"
