[SINGLE_KEYWORDS]
#KEYWORD; пробелы/отступы; другое(аргументы, доп. синтаксис) = [имя функци, *(строка - аргумент; число - индекс элемента строки)]
"UP[ \t]+[0-9]+" = ["self.move_player", "UP", 1]
"DOWN[ \t]+[0-9]+" = ["self.move_player", "DOWN", 1]
"LEFT[ \t]+[0-9]+" = ["self.move_player", "LEFT", 1]
"RIGHT[ \t]+[0-9]+" = ["self.move_player", "RIGHT", 1]
"SET[ \t]*[a-zA-Z]+[ \t]*=[ \t]*[0-9]+" = ["self.set_program_variable", 1, 3] # пока что необходимы пробелы рядом с символом =
"CALL[ \t]+[a-zA-Z]+" = ["self.call_procedure", 1]

#[DOUBLE_KEYWORDS.openers]
#"REPEAT[ \t]+[0-9]+" = ["self.get_repeating_sequence", 1]
#"(IFBLOCK)[ \t]+(LEFT|RIGHT|UP|DOWN)" = ["self.emptyfunc", 1]
#"PROCEDURE [a-zA-Z]+ \n.*\n ENDPROC" = ["self.emptyfunc", 1]


[DOUBLE_KEYWORDS]
"REPEAT[ \t]+[0-9]+" = "ENDREPEAT"
"(IFBLOCK)[ \t]+(LEFT|RIGHT|UP|DOWN)" = "ENDIF"
"PROCEDURE [a-zA-Z]+ \n.*\n ENDPROC" = "ENDPROC"