[SINGLE_KEYWORDS]
"UP [0-9]+" = ["local", "emptyfunc"]
"DOWN [0-9]+" = ["local", "emptyfunc"]
"LEFT [0-9]+" = ["local", "emptyfunc"]
"RIGHT [0-9]+" = ["local", "emptyfunc"]
"SET [a-zA-Z]+[ \t]*=[ \t]*[0-9]+" = ["local", "emptyfunc"]
"CALL[ \t]+[a-zA-Z]+" = ["local", "emptyfunc"]

[DOUBLE_KEYWORDS]
"IFBLOCK IF(UP|DOWN|LEFT|RIGHT). *ENDIF" = ["local", "emptyfunc"]
"REPEAT [1-9][0-9]* \n.*\n ENDREPEAT" = ["local", "emptyfunc"]
"PROCEDURE [a-zA-Z]+ \n.*\n ENDPROC" = ["local", "emptyfunc"]
